default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: raye7_CRUD_task_development

test:
  <<: *default
  database: raye7_CRUD_task_test

production:
  <<: *default
  database: raye7_CRUD_task_production
  username: raye7_CRUD_task
  password: <%= ENV['RAYE7_CRUD_TASK_DATABASE_PASSWORD'] %>
